# Generated by Django 2.2.10 on 2020-02-06 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=128)),
                ('required_arrival', models.DateTimeField()),
                ('number_of_owner_party', models.IntegerField()),
                ('number_of_sharer_party', models.IntegerField(default=0)),
                ('number_of_passenger', models.IntegerField(default=0)),
                ('vehicle_type', models.CharField(blank=True, choices=[('a', 'type a'), ('b', 'type b'), ('c', 'type c')], max_length=1)),
                ('Share_with_others', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('o', 'open'), ('f', 'confirmed'), ('c', 'completed')], default='o', max_length=1)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
